title:      ParsedOut.com
auto:       true
server:     true
pygments:   true
lsi:        true
paginate:   3
markdown:   maruku
maruku:
  use_divs:   true
  png_engine: blahtex
  use_tex:    true
  use_divs:   true
  png_dir:    images/latex
  png_url:    /images/latex/