title:      ParsedOut.com
baseurl:    http://parsedout.com
auto:       false
server:     false
pygments:   true
lsi:        true
paginate:   3
markdown:   maruku
permalink:  /:year/:month/:title/
maruku:
  use_divs:   true
  png_engine: blahtex
  use_tex:    true
  use_divs:   true
  png_dir:    images/latex
  png_url:    /images/latex/